### ISSUE TITLE
Misaligned Checkbox and not able to select all rows in IR

### ISSUE THREAD

**Issue by unficyp** [Pretius/pretius-smart-checkbox-column#1]
Thanks for the plugin, 
what could be the problem that:
- the checkbox and container is misaligned in an interactive report
- the selecting all rows only works when the "Select with click on row" feature is enabled ?
(see image)
![image](https://user-images.githubusercontent.com/1231087/184370340-6bf5d16b-9bef-4d2c-ab15-cd4663604461.png)

I'm not able to reproduce this on apex.oracle.com - it works there.
But i have 2 APEX 22.1.3 instances on 19c where i experience this behaviour.

**Comment by akierzkowski** [comment]
Hi, 
can you please share a version of plugin that you use (1.0 or 1.1) and the settings that you have configured for those plugin instances? Is there any custom CSS code on that page?

**Comment by unficyp** [comment]
Hi,
Plugin Version is 1.1.0 on both instances, both APEX Versions are 22.1.3 on 19c.

plugin_1.png:
newly created app, only 1 page, no custom css/js involved. selecting all only works when "select with click on row" is checked.
Dev console shows that there is no event listener present for the header checkbox (for rows the listener is present)
![plugin_1_no_event_listener](https://user-images.githubusercontent.com/1231087/185322720-3625dec1-ac63-4826-be10-652179d0ec21.png)

![plugin_1](https://user-images.githubusercontent.com/1231087/185320350-9daef48d-b045-4e2b-a752-fad329bfa6a7.png)

plugin_2:
older app but refreshed theme, no css/js involved.also no event listener on the header checkbox, misalignment can be solved checking "IR Limit column width" and resizing the browser window. same settings as in plugin_1.png

**Comment by akierzkowski** [comment]
I have prepared a patch version. Now after changes I'm not able to reproduce any of those bugs in any environment. Please check if this solution works for you as well.

**Comment by unficyp** [comment]
hi,
thanks - seems to work now !
